# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Titulo')),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('url', models.FileField(upload_to='data/', verbose_name='caminho')),
                ('sector', models.CharField(blank=True, max_length=200, verbose_name='setor')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.DataSet')),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='data',
            field=models.ManyToManyField(related_name='datasets', to='dashboards.DataSet'),
        ),
    ]
