# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_data_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='variable_type',
            field=models.CharField(default=324, max_length=200, verbose_name='type'),
            preserve_default=False,
        ),
    ]
