# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 02:51
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_dataset_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('url', models.FileField(upload_to='data/', verbose_name='caminho')),
            ],
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='url',
        ),
    ]
